#!/bin/bash

module purge
module load genomics

cd /mnt/mobydisk/pan/genomics/data/alee/nolan/projects/breast-mets/rna-seq/brain/BP29/BP29-qorts-v1.1.8
java -Xmx32G -jar /mnt/mobydisk/pan/genomics/data/alee/nolan/apps/QoRTs/QoRTs_1.1.8/QoRTs.jar QC --stranded /mnt/mobydisk/pan/genomics/data/alee/nolan/projects/breast-mets/rna-seq/brain/BP29/BP29-star-2.4.2a-counts-ensemblv80/BP29.star.sorted.bam /mnt/mobydisk/pan/genomics/data/alee/nolan/apps/star/reference-files/Homo_sapiens.GRCh38.80.gtf /mnt/mobydisk/pan/genomics/data/alee/nolan/projects/breast-mets/rna-seq/brain/BP29/BP29-qorts-v1.1.8


